spring.application.name=clinic-backend
server.port=${PORT:8080}

# Database Connection (MySQL / Aiven Cloud MySQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-d77214f-hemasree837-9e91.d.aivencloud.com:13392/defaultdb?useSSL=true&trustServerCertificate=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:avnadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.database-platform=${SPRING_JPA_PLATFORM:org.hibernate.dialect.MySQLDialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
