spring.application.name=clinic-backend
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://ballast.proxy.rlwy.net:28828/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:GILvavFrcSYgbDjeDZcTPWujJeubkXjz}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.database-platform=${SPRING_JPA_PLATFORM:org.hibernate.dialect.MySQLDialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
