spring.application.name=clinic-backend
server.port=${PORT:8080}
spring.datasource.url=${jdbc:mysql://ballast.proxy.rlwy.net:28828/railway}
spring.datasource.username=${root}
spring.datasource.password=${GILvavFrcSYgbDjeDZcTPWujJeubkXjz}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
